# Generated by Django 5.1.7 on 2025-04-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=6, null=True),
        ),
    ]
