# Generated by Django 5.1.7 on 2025-03-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(blank=True, choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('custom', 'Custom')], default='light', max_length=6, null=True),
        ),
    ]
